import { Flight } from '@/types';

export const mockFlights: Flight[] = [
  {
    id: '1',
    airline: 'Singapore Airlines',
    airlineLogo: 'SQ',
    departureTime: '12:10',
    arrivalTime: '15:30',
    departureAirport: 'Moi Intl, Mombasa Kenya',
    arrivalAirport: 'JFK Terminal, Nairobi, Kenya',
    duration: '3h 30min',
    stops: 0,
    price: 110,
    class: 'Business',
    refundable: true
  },
  {
    id: '2',
    airline: 'Qatar Airways',
    airlineLogo: 'QR',
    departureTime: '12:10',
    arrivalTime: '15:30',
    departureAirport: 'Moi Intl, Mombasa Kenya',
    arrivalAirport: 'JFK Terminal, Nairobi, Kenya',
    duration: '3h 30min',
    stops: 0,
    price: 435,
    class: 'Business',
    refundable: false
  },
  {
    id: '3',
    airline: 'Emirates',
    airlineLogo: 'EK',
    departureTime: '12:10',
    arrivalTime: '15:30',
    departureAirport: 'Moi Intl, Mombasa Kenya',
    arrivalAirport: 'JFK Terminal, Nairobi, Kenya',
    duration: '3h 30min',
    stops: 0,
    price: 330,
    class: 'Business',
    refundable: true
  },
  {
    id: '4',
    airline: 'Saudi Airlines',
    airlineLogo: 'SV',
    departureTime: '12:10',
    arrivalTime: '15:30',
    departureAirport: 'Moi Intl, Mombasa Kenya',
    arrivalAirport: 'JFK Terminal, Nairobi, Kenya',
    duration: '3h 30min',
    stops: 0,
    price: 200,
    class: 'Business',
    refundable: false
  },
  {
    id: '5',
    airline: 'Singapore Airlines',
    airlineLogo: 'SQ',
    departureTime: '12:10',
    arrivalTime: '15:30',
    departureAirport: 'Moi Intl, Mombasa Kenya',
    arrivalAirport: 'JFK Terminal, Nairobi, Kenya',
    duration: '3h 30min',
    stops: 0,
    price: 110,
    class: 'Business',
    refundable: true
  },
  {
    id: '6',
    airline: 'Lufthansa',
    airlineLogo: 'LH',
    departureTime: '06:45',
    arrivalTime: '10:15',
    departureAirport: 'Heathrow Airport, London',
    arrivalAirport: 'Charles de Gaulle, Paris',
    duration: '1h 30min',
    stops: 0,
    price: 180,
    class: 'Economy',
    refundable: true
  },
  {
    id: '7',
    airline: 'Air France',
    airlineLogo: 'AF',
    departureTime: '08:00',
    arrivalTime: '11:20',
    departureAirport: 'Berlin Brandenburg, Germany',
    arrivalAirport: 'Zurich Airport, Switzerland',
    duration: '1h 20min',
    stops: 0,
    price: 150,
    class: 'Economy',
    refundable: false
  },
  {
    id: '8',
    airline: 'British Airways',
    airlineLogo: 'BA',
    departureTime: '14:00',
    arrivalTime: '18:10',
    departureAirport: 'JFK Terminal, New York',
    arrivalAirport: 'LAX Terminal, Los Angeles',
    duration: '6h 10min',
    stops: 0,
    price: 350,
    class: 'Business',
    refundable: true
  },
  {
    id: '9',
    airline: 'Delta Airlines',
    airlineLogo: 'DL',
    departureTime: '17:30',
    arrivalTime: '21:00',
    departureAirport: 'Logan Intl, Boston',
    arrivalAirport: 'O\'Hare Intl, Chicago',
    duration: '2h 30min',
    stops: 0,
    price: 220,
    class: 'Economy',
    refundable: false
  },
  {
    id: '10',
    airline: 'KLM Royal Dutch',
    airlineLogo: 'KL',
    departureTime: '09:25',
    arrivalTime: '13:40',
    departureAirport: 'Schiphol, Amsterdam',
    arrivalAirport: 'Vienna Intl, Austria',
    duration: '2h 15min',
    stops: 0,
    price: 275,
    class: 'Business',
    refundable: true
  },
  {
    id: '11',
    airline: 'Turkish Airlines',
    airlineLogo: 'TK',
    departureTime: '10:15',
    arrivalTime: '15:00',
    departureAirport: 'Istanbul Airport, Turkey',
    arrivalAirport: 'Ataturk Airport, Turkey',
    duration: '2h 45min',
    stops: 0,
    price: 295,
    class: 'Business',
    refundable: false
  },
  {
    id: '12',
    airline: 'Etihad Airways',
    airlineLogo: 'EY',
    departureTime: '23:10',
    arrivalTime: '06:45',
    departureAirport: 'Abu Dhabi Intl, UAE',
    arrivalAirport: 'Heathrow Airport, London',
    duration: '7h 35min',
    stops: 0,
    price: 410,
    class: 'Business',
    refundable: true
  },
  {
    id: '13',
    airline: 'Alaska Airlines',
    airlineLogo: 'AS',
    departureTime: '15:20',
    arrivalTime: '19:50',
    departureAirport: 'Seattle-Tacoma Intl, USA',
    arrivalAirport: 'Denver Intl, USA',
    duration: '2h 30min',
    stops: 0,
    price: 185,
    class: 'Economy',
    refundable: false
  },
  {
    id: '14',
    airline: 'Air India',
    airlineLogo: 'AI',
    departureTime: '05:30',
    arrivalTime: '09:15',
    departureAirport: 'Indira Gandhi Intl, Delhi',
    arrivalAirport: 'Chhatrapati Shivaji Intl, Mumbai',
    duration: '2h 45min',
    stops: 0,
    price: 160,
    class: 'Economy',
    refundable: true
  },
  {
    id: '15',
    airline: 'Malaysia Airlines',
    airlineLogo: 'MH',
    departureTime: '11:50',
    arrivalTime: '14:40',
    departureAirport: 'Kuala Lumpur Intl, Malaysia',
    arrivalAirport: 'Suvarnabhumi, Bangkok',
    duration: '1h 50min',
    stops: 0,
    price: 140,
    class: 'Economy',
    refundable: true
  }
];

export const packages = [
  {
    id: 1,
    title: 'Bali Adventure',
    location: 'Bali, Indonesia',
    image: 'https://images.pexels.com/photos/2166559/pexels-photo-2166559.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 899,
    rating: 4.8,
    duration: '7 days',
    description: 'Enjoy a perfect mix of beaches, temples, and tropical fun in vibrant Bali.',
    highlights: ['Beachfront Resort', 'Temple Tours', 'Volcano Hike', 'Traditional Spa'],
    refundable: true
  },
  {
    id: 2,
    title: 'Tokyo Explorer',
    location: 'Tokyo, Japan',
    image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1299,
    rating: 4.9,
    duration: '5 days',
    description: 'Dive into Tokyo’s tech-savvy streets and rich cultural heritage.',
    highlights: ['Shibuya Crossing', 'Sushi Workshop', 'Mt. Fuji View', 'Anime City Tour'],
    refundable: false
  },
  {
    id: 3,
    title: 'Santorini Escape',
    location: 'Santorini, Greece',
    image: 'https://images.pexels.com/photos/1285625/pexels-photo-1285625.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1599,
    rating: 4.7,
    duration: '6 days',
    description: 'Unwind on sun-soaked cliffs with endless blue ocean views.',
    highlights: ['White Cliff Villas', 'Wine Tasting', 'Sunset Cruise', 'Ancient Ruins'],
    refundable: true
  },
  {
    id: 4,
    title: 'Dubai Luxury',
    location: 'Dubai, UAE',
    image: 'https://images.pexels.com/photos/1470502/pexels-photo-1470502.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 2199,
    rating: 4.9,
    duration: '4 days',
    description: 'Experience pure luxury with skyscrapers, desert safaris, and shopping.',
    highlights: ['Burj Khalifa Tour', '5-Star Hotel Stay', 'Desert Safari', 'Luxury Yacht Ride'],
    refundable: false
  },
  {
    id: 5,
    title: 'Paris Getaway',
    location: 'Paris, France',
    image: 'https://images.pexels.com/photos/338515/pexels-photo-338515.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1799,
    rating: 4.6,
    duration: '5 days',
    description: 'Explore the romantic city of lights, art, and fine cuisine.',
    highlights: ['Eiffel Tower', 'Louvre Museum', 'River Seine Cruise', 'Champs-Élysées Shopping'],
    refundable: true
  },
  {
    id: 6,
    title: 'New York Highlights',
    location: 'New York, USA',
    image: 'https://images.pexels.com/photos/466685/pexels-photo-466685.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1499,
    rating: 4.8,
    duration: '6 days',
    description: 'See NYC’s iconic skyline, Broadway lights, and cultural landmarks.',
    highlights: ['Statue of Liberty', 'Central Park', 'Times Square', 'Broadway Show'],
    refundable: false
  },
  {
    id: 7,
    title: 'Sydney Discovery',
    location: 'Sydney, Australia',
    image: 'https://images.pexels.com/photos/2193300/pexels-photo-2193300.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1899,
    rating: 4.7,
    duration: '7 days',
    description: 'Discover beaches, nature, and Aussie culture in vibrant Sydney.',
    highlights: ['Sydney Opera House', 'Blue Mountains', 'Bondi Beach', 'Harbor Dinner Cruise'],
    refundable: true
  },
  {
    id: 8,
    title: 'Rome Heritage Tour',
    location: 'Rome, Italy',
    image: 'https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1399,
    rating: 4.5,
    duration: '5 days',
    description: 'Walk through history in Rome’s ancient ruins and timeless streets.',
    highlights: ['Colosseum Tour', 'Vatican Visit', 'Trevi Fountain', 'Pasta Making Class'],
    refundable: true
  },
  {
    id: 9,
    title: 'Cairo Pyramids',
    location: 'Cairo, Egypt',
    image: 'https://images.pexels.com/photos/2402921/pexels-photo-2402921.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1099,
    rating: 4.6,
    duration: '6 days',
    description: 'Explore the wonders of the Pharaohs and cruise the Nile.',
    highlights: ['Great Pyramids', 'Sphinx Visit', 'Camel Ride', 'Nile Dinner Cruise'],
    refundable: false
  },
  {
    id: 10,
    title: 'Barcelona Beaches',
    location: 'Barcelona, Spain',
    image: 'https://images.pexels.com/photos/861509/pexels-photo-861509.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1299,
    rating: 4.7,
    duration: '5 days',
    description: 'Relax on Mediterranean beaches with Gaudí’s art in the background.',
    highlights: ['La Sagrada Família', 'Tapas Tour', 'Beach Relaxation', 'Flamenco Show'],
    refundable: true
  },
  {
    id: 11,
    title: 'Iceland Northern Lights',
    location: 'Reykjavík, Iceland',
    image: 'https://images.pexels.com/photos/1533720/pexels-photo-1533720.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 2299,
    rating: 4.9,
    duration: '4 days',
    description: 'Chase the aurora and soak in geothermal wonders of Iceland.',
    highlights: ['Northern Lights Hunt', 'Blue Lagoon', 'Golden Circle Tour', 'Glacier Hike'],
    refundable: true
  },
  {
    id: 12,
    title: 'Bangkok Culture Tour',
    location: 'Bangkok, Thailand',
    image: 'https://images.pexels.com/photos/2480618/pexels-photo-2480618.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 999,
    rating: 4.6,
    duration: '5 days',
    description: 'Discover Thai temples, street food, and floating markets.',
    highlights: ['Grand Palace', 'Floating Market', 'Thai Massage', 'Street Food Tour'],
    refundable: false
  },
  {
    id: 13,
    title: 'Petra Adventure',
    location: 'Petra, Jordan',
    image: 'https://images.pexels.com/photos/2611697/pexels-photo-2611697.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1199,
    rating: 4.8,
    duration: '4 days',
    description: 'Trek through ancient sandstone cities and red desert trails.',
    highlights: ['Petra Treasury', 'Wadi Rum Jeep Tour', 'Bedouin Camp', 'Camel Trek'],
    refundable: true
  },
  {
    id: 14,
    title: 'Cape Town Safari',
    location: 'Cape Town, South Africa',
    image: 'https://images.pexels.com/photos/2090651/pexels-photo-2090651.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1599,
    rating: 4.7,
    duration: '6 days',
    description: 'Experience wild safaris and ocean views in one exotic location.',
    highlights: ['Table Mountain', 'Big Five Safari', 'Wine Tour', 'Penguin Beach'],
    refundable: false
  },
  {
    id: 15,
    title: 'Machu Picchu Trail',
    location: 'Cusco, Peru',
    image: 'https://images.pexels.com/photos/1226302/pexels-photo-1226302.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: 1899,
    rating: 4.9,
    duration: '7 days',
    description: 'Follow the ancient Inca Trail to one of the world’s greatest wonders.',
    highlights: ['Inca Trail Trek', 'Sacred Valley', 'Local Markets', 'Machu Picchu Ruins'],
    refundable: true
  }
];
